name: Destroy Resources
description: Use this template to request the destruction of resources.
title: "[DESTROY] Request to Destroy Resources"
labels: ["destroy"]

body:
  - type: markdown
    attributes:
      value: |
        ## Destroy Resources Request

        Please provide the following information to request the destruction of resources.

  - type: input
    id: resource_name
    attributes:
      label: ">>resource_name<<"
      description: Name of the resource to be destroyed.
      placeholder: e.g., my-resource

  - type: dropdown
    id: resource_type
    attributes:
      label: ">>resource_type<<"
      description: Select the type of resource to be destroyed.
      options:
        - S3 Bucket
        - IAM Role
        - IAM Policy

  - type: textarea
    id: reason
    attributes:
      label: ">>reason<<"
      description: Provide a reason for why this resource should be destroyed.
      placeholder: ex No longer needed, cost-saving, etc.
