name: 03 - Build and Deploy to HOM on AWS 

on:
  pull_request:
    branches:
      - 'release/*'
    types: [closed]

jobs:
  get-version:
    if: github.event.pull_request.merged == true
    runs-on: ubuntu-latest
    outputs:
      new_version: ${{ steps.get_version.outputs.version }}
    steps:
      - name: Get version
        id: get_version
        run: |
          VERSION=$(echo "${{ github.event.pull_request.title }}" | grep -oP 'release/v\K[0-9]+\.[0-9]+\.[0-9]+')
          echo "version=${VERSION}" >> $GITHUB_OUTPUT

  infra-terraform:
    needs: get-version
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Create Pull Request to Main
        uses: peter-evans/create-pull-request@v7
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          base: main
          branch: release/${{ needs.get-version.outputs.new_version }}
          title: 'Branch criada automaticamente -> main'
          body: 'This PR was automatically created by GitHub Actions.'
          draft: false

  create-tag-release:
    runs-on: ubuntu-latest
    needs: [ infra-terraform, get-version ]
    steps:
      - name: Create tag
        if: steps.get_version.outputs.version != ''
        run: |
          git config user.name github-actions
          git config user.email github-actions@github.com
          git tag ${{ needs.get-version.outputs.new_version }}
          git push origin ${{ needs.get-version.outputs.new_version }}         