name: 04 - Build and Deploy to PROD on AWS

on:
  pull_request:
    branches: 
      - main
    types: [edited]

jobs:
  get-version:
    if: startsWith(github.head_ref, 'release/')
    runs-on: ubuntu-latest
    needs: infra-terraform
    outputs:
      version: ${{ steps.get_version.outputs.version }}
    steps:
      - name: Get version
        id: get_version
        run: |
          VERSION=$(echo "${{ github.head_ref }}" | grep -oP 'release/v\K[0-9]+\.[0-9]+\.[0-9]+')
          echo "version=${VERSION}" >> $GITHUB_OUTPUT

  infra-terraform:
    if: startsWith(github.head_ref, 'release/')
    runs-on: ubuntu-latest
    needs: get-version
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

  create-tag-release:
    if: github.event.pull_request.merged == true
    runs-on: ubuntu-latest
    needs: [ infra-terraform, get-version ]
    steps:
      - name: Create tag
        if: needs.get_version.outputs.version != ''
        run: |
          git config user.name github-actions
          git config user.email github-actions@github.com
          git tag ${{ needs.get-version.outputs.version }}
          git push origin ${{ needs.get-version.outputs.version }}

      - name: Create GitHub Release
        if: needs.get_version.outputs.version != ''
        uses: actions/create-release@v1
        with:
          tag_name: ${{ needs.get-version.outputs.version }}
          release_name: Release ${{ needs.get-version.outputs.version }}
          body: |
            Release ${{ needs.get-version.outputs.version }} is now available.
              draft: false
              prerelease: false
            env:
              GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}